# Python Lists

## Creating

In [76]:
# this is a python list
a = [42, 7, 13, 24601, 2001, 3.50]

In [77]:
# this is a list comprehension -- think of it as a sexy for loop

# the following gives us a list in which we multiplied each element in a by 2
z = [i * 2 for i in a]
z

[84, 14, 26, 49202, 4002, 7.0]

## Indexing

In [78]:
# you can index into it
a[0]

42

In [79]:
# what's the 3rd element?
a[2]

13

In [80]:
# indices can also be negative
# this gives you the last element
a[-1]

3.5

## Slicing

In [81]:
# you can also get subsets of the list with slicing
#     a[start:end]
# [start, end)

# this returns the 3rd and 4th entries (indices 2 and 3 -- note we exclude 4!)
a[2:4]

[13, 24601]

In [82]:
# if you leave one side blank, it automatically goes all the way
# first five:
a[:5]

[42, 7, 13, 24601, 2001]

In [83]:
# how do you get the last three elements?
a[-3:]

[24601, 2001, 3.5]

In [84]:
# slices can also skip numbers
# a[start:end:interval]

# this gives us every other number, starting with the first
a[::2]

[42, 13, 2001]

In [85]:
# the interval can also be negative
# what does that do?
# it makes it go backwards (in reverse order)
a[::-2]

[3.5, 24601, 7]

# Numpy

In [86]:
import numpy as np

## Creating

In [87]:
# numpy arrays can be created from a python list
b = np.array(a)
b

array([4.2000e+01, 7.0000e+00, 1.3000e+01, 2.4601e+04, 2.0010e+03,
       3.5000e+00])

Right now, it looks an awful like a python list, but there are some key points you should know.

numpy arrays are:
- homogeneous (all elements in an array have the same type)
- multidimensional

In [88]:
# Homogeneous: all numpy arrays have an associated data type.
# numbers are usually ints or floats
b.dtype

dtype('float64')

In [89]:
# Multidimensional: numpy arrays can have multiple dimensions, like a nested list.
# We can reshape b into a 3x2 matrix
# Note: this doesn't change b. That's why we assign it to a new variable: m
m = b.reshape(3, 2)
m

array([[4.2000e+01, 7.0000e+00],
       [1.3000e+01, 2.4601e+04],
       [2.0010e+03, 3.5000e+00]])

In [90]:
# Each dimension is called an axis
# The size across each axis is called the shape
# These are two very important concepts!
m.shape

(3, 2)

## Indexing

In [91]:
# We index into numpy arrays much the same way as python lists.
b[0]

42.0

In [149]:
# But N-dimensional arrays mean we can be more expressive with indexing
# This gives us [0th index of axis 0, 1st index of axis 1]
# You can think of this as a grid
# Alternatively, this is like m[0][1]
m[2, 1]

3.5

In [93]:
# We can also pass in multiple indices as a list
# This gives us the 1st, 2nd, and 5th values of b
b[[0, 1, 4]]

array([  42.,    7., 2001.])

In [154]:
# Let's combine these two facts to get the 2nd and 3rd items in the second column of m
m[(2,1),(1,1)]

array([3.5000e+00, 2.4601e+04])

In [95]:
# We can also incorporate our previous knowledge of slices.
# So to get the second column
# This gives us the entire range on axis 0, and only the 1st index on axis 1
m[:,1]

array([7.0000e+00, 2.4601e+04, 3.5000e+00])

## Math

In [96]:
# numpy gives us a lot of math functions to work with
# I'll only show you a couple, but you can find them all in the documentation

np.sum(b)  # guess what this does?

26667.5

In [97]:
np.mean(b)  # and this?

4444.583333333333

In [98]:
# for convenience, you can also call
b.mean()

4444.583333333333

In [99]:
# you can also apply these functions to only one axis
# only sum across rows (read: apply the sum to axis 1)
np.sum(m, axis=1)

array([   49. , 24614. ,  2004.5])

In [100]:
# numpy has a concept called podcasting
# It tries to coerce non-matching shapes.
# 2 is a scalar, but we can still multiply m by it
# it just repeats the 2 across all instances of m
m * 2

array([[8.4000e+01, 1.4000e+01],
       [2.6000e+01, 4.9202e+04],
       [4.0020e+03, 7.0000e+00]])

# Pandas

In [101]:
import pandas as pd

## Creating

Pandas lets us read all sorts of data into a Dataframe. Think of this as a series of lists. Let's look at an example.

In [102]:
df = pd.read_csv("./cereal.csv")
type(df)

pandas.core.frame.DataFrame

In [103]:
# head() gives us the first 10 rows in the dataframe (pd.DataFrame)
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [104]:
# you can think of each column as a list (or a 1D numpy array)
# in practice, these are called pandas Series (pd.Series)
# you can index into the dataframe with a string to get one column
df["name"]

0                     100% Bran
1             100% Natural Bran
2                      All-Bran
3     All-Bran with Extra Fiber
4                Almond Delight
                ...            
72                      Triples
73                         Trix
74                   Wheat Chex
75                     Wheaties
76          Wheaties Honey Gold
Name: name, Length: 77, dtype: object

In [105]:
type(df["name"])

pandas.core.series.Series

## Pandas Series vs Numpy Arrays

In [106]:
# There are many similarities between pd.Series and np.ndarray
# for example:
df["carbo"].mean()

14.597402597402597

In [107]:
# In fact, we can turn pd.Series into a numpy array
# again, this returns a numpy array -- df["carbo"] doesn't change.
df["carbo"].to_numpy()

array([ 5. ,  8. ,  7. ,  8. , 14. , 10.5, 11. , 18. , 15. , 13. , 12. ,
       17. , 13. , 13. , 12. , 22. , 21. , 13. , 12. , 10. , 21. , 21. ,
       11. , 18. , 11. , 14. , 14. , 12. , 14. , 13. , 11. , 15. , 15. ,
       17. , 13. , 12. , 11.5, 14. , 17. , 20. , 21. , 12. , 12. , 16. ,
       16. , 16. , 17. , 15. , 15. , 21. , 18. , 13.5, 11. , 20. , 13. ,
       10. , 14. , -1. , 14. , 10.5, 15. , 23. , 22. , 16. , 19. , 20. ,
        9. , 16. , 15. , 21. , 15. , 16. , 21. , 13. , 17. , 17. , 16. ])

In [108]:
# The key difference is that Series are indexed
# See the 0, 1, ... 76 on the left? That is the index of each item.
# Right now they are just positions, but theoretically they can be any unique identifier for the row
# Think: ID, username, etc
df["carbo"].index

RangeIndex(start=0, stop=77, step=1)

## Indexing into DataFrames and Series

In [109]:
# Indexing is a little bit different in pandas.
# One parallel to what you've been used to is .loc[]
# this is the row at index 0
df.loc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [110]:
# multiple indices work
df.loc[[1, 2, 3]]

name mfr type  calories  protein  fat  sodium  fiber  \
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912

In [111]:
# caveat: remember that pandas doesn't require zero-indexing. indices can be anything.
# this means slicing might not work all the time (what would df.loc["asdf":"hjkl"] even mean?)
# in the cases that you actually want to index by row number, you can always do that with .iloc[]
# again, this will behave the same as .loc[] with our dataset because our data is 0-indexed
df.iloc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [112]:
# We can also use boolean indexing by passing a list of booleans like so:
df[[True] + [False] * 76]
# Let me explain:
# - [True] + [False] * 76 gives us a list that looks like [True, False, ..., False] with 1 True and 76 Falses
# - This matches the number of rows in our data (77)
# - pandas returns all the rows with a corresponding True (in this case, only the first one)

name mfr type  calories  protein  fat  sodium  fiber  carbo  sugars  \
0  100% Bran   N    C        70        4    1     130   10.0    5.0       6   

   potass  vitamins  shelf  weight  cups     rating  
0     280        25      3     1.0  0.33  68.402973

In [113]:
# This is powerful because we can also make comparisons with Series and values.
df["protein"] > 3

0      True
1     False
2      True
3      True
4     False
      ...  
72    False
73    False
74    False
75    False
76    False
Name: protein, Length: 77, dtype: bool

In [114]:
# Combining these two things, we have a very expressive way of filtering.
# This gives us all the rows in which the protein is greater than 3.
df[df["protein"] > 3]

name mfr type  calories  protein  fat  \
0                           100% Bran   N    C        70        4    1   
2                            All-Bran   K    C        70        4    1   
3           All-Bran with Extra Fiber   K    C        50        4    0   
11                           Cheerios   G    C       110        6    2   
41                               Life   Q    C       100        4    2   
43                              Maypo   A    H       100        4    1   
44   Muesli Raisins; Dates; & Almonds   R    C       150        4    3   
45  Muesli Raisins; Peaches; & Pecans   R    C       150        4    3   
56                 Quaker Oat Squares   Q    C       100        4    1   
57                     Quaker Oatmeal   Q    H       100        5    2   
67                          Special K   K    C       110        6    0   

    sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0      130   10.0    5.0       6     280        25      3     1.0  0.33   
2      260    9.0    7.0       5     320        25      3     1.0  0.33   
3      140   14.0    8.0       0     330        25      3     1.0  0.50   
11     290    2.0   17.0       1     105        25      1     1.0  1.25   
41     150    2.0   12.0       6      95        25      2     1.0  0.67   
43       0    0.0   16.0       3      95        25      2     1.0  1.00   
44      95    3.0   16.0      11     170        25      3     1.0  1.00   
45     150    3.0   16.0      11     170        25      3     1.0  1.00   
56     135    2.0   14.0       6     110        25      3     1.0  0.50   
57       0    2.7   -1.0      -1     110         0      1     1.0  0.67   
67     230    1.0   16.0       3      55        25      1     1.0  1.00   

       rating  
0   68.402973  
2   59.425505  
3   93.704912  
11  50.764999  
41  45.328074  
43  54.850917  
44  37.136863  
45  34.139765  
56  49.511874  
57  50.828392  
67  53.131324

## Manipulating Series

Often when we're preprocessing data, we want to make uniform changes to a specific column. We can do this by applying functions.

In [115]:
# Suppose we want to make the cereals more appetizing.
# Let's add "Delicious " to the beginning of every name.

# The pattern is we define a function for a single entry
def make_delicious(name):
    return "Delicious " + name

# and then call apply on the series to apply the function to each element in the series
df["name"].apply(make_delicious)

0                     Delicious 100% Bran
1             Delicious 100% Natural Bran
2                      Delicious All-Bran
3     Delicious All-Bran with Extra Fiber
4                Delicious Almond Delight
                     ...                 
72                      Delicious Triples
73                         Delicious Trix
74                   Delicious Wheat Chex
75                     Delicious Wheaties
76          Delicious Wheaties Honey Gold
Name: name, Length: 77, dtype: object

In [116]:
# this returns the changes, but doesn't apply them in place.
# that means on our original dataframe, the cereals are still bland
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [117]:
# we can fix this by assigning the new names to the column.
df["name"] = df["name"].apply(make_delicious)
df.head()

name mfr type  calories  protein  fat  \
0                  Delicious 100% Bran   N    C        70        4    1   
1          Delicious 100% Natural Bran   Q    C       120        3    5   
2                   Delicious All-Bran   K    C        70        4    1   
3  Delicious All-Bran with Extra Fiber   K    C        50        4    0   
4             Delicious Almond Delight   R    C       110        2    2   

   sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0     130   10.0    5.0       6     280        25      3     1.0  0.33   
1      15    2.0    8.0       8     135         0      3     1.0  1.00   
2     260    9.0    7.0       5     320        25      3     1.0  0.33   
3     140   14.0    8.0       0     330        25      3     1.0  0.50   
4     200    1.0   14.0       8      -1        25      3     1.0  0.75   

      rating  
0  68.402973  
1  33.983679  
2  59.425505  
3  93.704912  
4  34.384843

In [159]:
# here's another example.
# Jackson is a skeptic and doesn't believe calling things "Delicious" makes them taste better.
# But he does think adding sugar will make them taste better.
# How can we add 10 grams of sugar to every cereal?
df["sugars"] = df["sugars"].apply(lambda x : x + 10)
df.head()

name mfr type  calories  protein  fat  \
0                  Delicious 100% Bran   N    C        70        4    1   
1          Delicious 100% Natural Bran   Q    C       120        3    5   
2                   Delicious All-Bran   K    C        70        4    1   
3  Delicious All-Bran with Extra Fiber   K    C        50        4    0   
4             Delicious Almond Delight   R    C       110        2    2   

   sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0     130   10.0    5.0      16     280        25      3     1.0  0.33   
1      15    2.0    8.0      18     135         0      3     1.0  1.00   
2     260    9.0    7.0      15     320        25      3     1.0  0.33   
3     140   14.0    8.0      10     330        25      3     1.0  0.50   
4     200    1.0   14.0      18      -1        25      3     1.0  0.75   

      rating  
0  68.402973  
1  33.983679  
2  59.425505  
3  93.704912  
4  34.384843

## Groups and Aggregates

When we have lots and lots of data, it's more useful to look at aggregate statistics like the mean or median. But sometimes we lose too much detail aggregating across the whole dataset.

The solution is to aggregate across groups. For example, maybe we're less interested in the mean calorie count of all cereals and more interested in the mean for each manufacturer.

In [160]:
# First, we can see how many (and which) unique manufacturers there are
# Note: this gives us a numpy array
df["mfr"].unique()

array(['N', 'Q', 'K', 'R', 'G', 'P', 'A'], dtype=object)

In [161]:
# Now let's group by the manufacturers
# This gives us a groupby object across the dataframe
mfrs = df.groupby("mfr")
mfrs

In [162]:
# what happens if we try to access the calories column?
mfrs["calories"]

In [163]:
# now let's try to get the mean
mfrs["calories"].mean()

mfr
A    100.000000
G    111.363636
K    108.695652
N     86.666667
P    108.888889
Q     95.000000
R    115.000000
Name: calories, dtype: float64

In [164]:
# we can also aggregate across multiple columns, and even use different aggregations
# let's get the average calorie count but the maximum protein
mfrs[["calories", "protein"]].agg({"calories": "mean", "protein": "max"})

calories  protein
mfr                     
A    100.000000        4
G    111.363636        6
K    108.695652        6
N     86.666667        4
P    108.888889        3
Q     95.000000        5
R    115.000000        4

# Exercises

Unless otherwise noted, these should be one line of code.

In [186]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a
x_a = a[-3:]
# reverse the list
y_a = reversed(a)
# get a list where each entry in a is cubed (so the new list is [1, 4, 9, 16, 25, 36])
z_a = [i*i*i for i in a]

In [187]:
# create a numpy array from this list
b = np.array(a)
print(b)

[1 2 3 4 5 6]


In [188]:
# find the mean of b
b.mean()

3.5

In [190]:
# change b from a length-6 list to a 2x3 matrix
b = b.reshape(2,3)

In [191]:
# find the mean value of each row
b.mean(axis=1)

array([2., 5.])

In [170]:
# find the mean value of each column
b.mean(axis=2)

In [193]:
# find the third column of b
b[:,[-1]]

array([[3],
       [6]])

In [273]:
# get a list where each entry in b is cubed (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
np.power(b.reshape(1,6),2)

array([[ 1,  4,  9, 16, 25, 36]])

In [267]:
# load in the "starbucks.csv" dataset
bucks_df = pd.read_csv("starbucks.csv")

In [200]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
bucks_df["Calories"].mean()

193.87190082644628

In [209]:
# how many different categories of beverages are there?
len(bucks_df["Beverage"].unique())

33

In [215]:
# what is the average # calories for each beverage category?
bucks_df.groupby("Beverage").mean()

139.166667   
Caffè Mocha (Without Whipped Cream)                 210.000000   
Cappuccino                                           90.000000   
Caramel                                             150.000000   
Caramel (Without Whipped Cream)                     268.888889   
Caramel Apple Spice (Without Whipped Cream)         247.500000   
Caramel Macchiato                                   184.166667   
Coffee                                              210.000000   
Espresso                                              7.500000   
Hot Chocolate (Without Whipped Cream)               236.666667   
Iced Brewed Coffee (With Classic Syrup)              93.333333   
Iced Brewed Coffee (With Milk & Classic Syrup)      122.222222   
Java Chip                                           220.000000   
Java Chip (Without Whipped Cream)                   327.777778   
Mocha                                               156.666667   
Mocha (Without Whipped Cream)                       272.222222   
Orange Mango Banana Smoothie                        266.666667   
Shaken Iced Tazo® Tea (With Classic Syrup)           86.666667   
Shaken Iced Tazo® Tea Lemonade (With Classic Sy...  140.000000   
Skinny Latte (Any Flavour)                          110.000000   
Strawberries & Crème (Without Whipped Cream)        248.888889   
Strawberry Banana Smoothie                          290.000000   
Tazo® Chai Tea Latte                                196.666667   
Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)     148.333333   
Tazo® Full-Leaf Tea Latte                           148.333333   
Tazo® Green Tea Latte                               275.000000   
Tazo® Tea                                             0.000000   
Vanilla Bean (Without Whipped Cream)                197.500000   
Vanilla Latte (Or Other Flavoured Latte)            195.833333   
White Chocolate Mocha (Without Whipped Cream)       330.000000   

                                                    Trans Fat (g)   \
Beverage                                                             
Banana Chocolate Smoothie                                 1.833333   
Brewed Coffee                                             0.000000   
Caffè Americano                                           0.000000   
Caffè Latte                                               1.350000   
Caffè Mocha (Without Whipped Cream)                       2.375000   
Cappuccino                                                0.833333   
Caramel                                                   0.066667   
Caramel (Without Whipped Cream)                           0.822222   
Caramel Apple Spice (Without Whipped Cream)               0.000000   
Caramel Macchiato                                         1.708333   
Coffee                                                    0.633333   
Espresso                                                  0.000000   
Hot Chocolate (Without Whipped Cream)                     2.458333   
Iced Brewed Coffee (With Classic Syrup)                   0.000000   
Iced Brewed Coffee (With Milk & Classic Syrup)            0.277778   
Java Chip                                                 3.000000   
Java Chip (Without Whipped Cream)                         3.888889   
Mocha                                                     0.466667   
Mocha (Without Whipped Cream)                             1.266667   
Orange Mango Banana Smoothie                              0.400000   
Shaken Iced Tazo® Tea (With Classic Syrup)                0.000000   
Shaken Iced Tazo® Tea Lemonade (With Classic Sy...        0.000000   
Skinny Latte (Any Flavour)                                0.150000   
Strawberries & Crème (Without Whipped Cream)              0.844444   
Strawberry Banana Smoothie                                0.566667   
Tazo® Chai Tea Latte                                      0.783333   
Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)           0.733333   
Tazo® Full-Leaf Tea Latte                

In [233]:
# what beverage preparation includes the most sugar?
bucks_df.groupby("Beverage").mean()["Sugars (g)"].sort_values()
# Java Chip (Without Whipped Cream)                      62.444444

Beverage
Brewed Coffee                                           0.000000
Caffè Americano                                         0.000000
Tazo® Tea                                               0.000000
Espresso                                                0.000000
Cappuccino                                              8.083333
Caffè Latte                                            12.916667
Skinny Latte (Any Flavour)                             14.500000
Iced Brewed Coffee (With Classic Syrup)                22.333333
Shaken Iced Tazo® Tea (With Classic Syrup)             22.333333
Tazo® Full-Leaf Tea Latte                              25.333333
Iced Brewed Coffee (With Milk & Classic Syrup)         25.333333
Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)        25.333333
Caramel Macchiato                                      25.416667
Caffè Mocha (Without Whipped Cream)                    27.833333
Vanilla Latte (Or Other Flavoured Latte)               28.333333
Mocha           

In [258]:
# what is the average % daily value calcium content for each beverage?
# HINT: make sure your columns have the datatypes you want
# (you can use more than one line for this one)
copy = bucks_df
# copy[" Calcium (% DV) "] = copy[" Calcium (% DV) "].apply(lambda x : float(x[:-1]))
copy.groupby("Beverage")[" Calcium (% DV) "].mean()

Beverage
Banana Chocolate Smoothie                              20.000000
Brewed Coffee                                           0.500000
Caffè Americano                                         1.500000
Caffè Latte                                            35.000000
Caffè Mocha (Without Whipped Cream)                    30.000000
Cappuccino                                             22.500000
Caramel                                                11.000000
Caramel (Without Whipped Cream)                        12.000000
Caramel Apple Spice (Without Whipped Cream)             0.000000
Caramel Macchiato                                      28.333333
Coffee                                                 12.333333
Espresso                                                0.000000
Hot Chocolate (Without Whipped Cream)                  35.000000
Iced Brewed Coffee (With Classic Syrup)                 0.000000
Iced Brewed Coffee (With Milk & Classic Syrup)          8.000000
Java Chip       

In [272]:
# It's bulking season. What drink should Jackson get so that he maximizes protein but minimizes fat?
# (you can use more than one line for this one) # ' Protein (g) ' 'Total Fat (g)'
copy2 = bucks_df
copy2['Total Fat (g)'] = copy2['Total Fat (g)'].apply(lambda x : -float(x))
copy2.groupby("Beverage").mean().sort_values(by=[' Protein (g) ', 'Total Fat (g)'],ascending=False)
# Banana Choclate Smoothie or Orange Mango Banana Smoothie

166667      -3.791667   
Vanilla Latte (Or Other Flavoured Latte)            195.833333      -3.575000   
Caramel Macchiato                                   184.166667      -3.958333   
Cappuccino                                           90.000000      -2.466667   
Tazo® Chai Tea Latte                                196.666667      -2.400000   
Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)     148.333333      -2.175000   
Tazo® Full-Leaf Tea Latte                           148.333333      -2.175000   
Java Chip                                           220.000000      -4.000000   
Java Chip (Without Whipped Cream)                   327.777778      -5.777778   
Mocha (Without Whipped Cream)                       272.222222      -2.555556   
Mocha                                               156.666667      -0.833333   
Strawberries & Crème (Without Whipped Cream)        248.888889      -2.244444   
Vanilla Bean (Without Whipped Cream)                197.500000      -1.300000   
Coffee                                              210.000000      -1.383333   
Caramel                                             150.000000      -0.100000   
Caramel (Without Whipped Cream)                     268.888889      -1.866667   
Iced Brewed Coffee (With Milk & Classic Syrup)      122.222222      -0.922222   
Caffè Americano                                      13.750000       0.000000   
Espresso                                              7.500000       0.000000   
Brewed Coffee                                         4.250000      -0.100000   
Iced Brewed Coffee (With Classic Syrup)              93.333333      -0.066667   
Shaken Iced Tazo® Tea Lemonade (With Classic Sy...  140.000000       0.000000   
Caramel Apple Spice (Without Whipped Cream)         247.500000       0.000000   
Shaken Iced Tazo® Tea (With Classic Syrup)           86.666667       0.000000   
Tazo® Tea                                             0.000000       0.000000   

                                                    Trans Fat (g)   \
Beverage                                                             
Banana Chocolate Smoothie                                 1.833333   
Strawberry Banana Smoothie                                0.566667   
Orange Mango Banana Smoothie                              0.400000   
White Chocolate Mocha (Without Whipped Cream)             4.875000   
Hot Chocolate (Without Whipped Cream)                     2.458333   
Tazo® Green Tea Latte                                     1.475000   
Caffè Mocha (Without Whipped Cream)                       2.375000   
Skinny Latte (Any Flavour)                                0.150000   
Caffè Latte                                               1.350000   
Vanilla Latte (Or Other Flavoured Latte)                  1.241667   
Caramel Macchiato                                         1.708333   
Cappuccino                                                0.833333   
Tazo® Chai Tea Latte                                      0.783333   
Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)           0.733333   
Tazo® Full-Leaf Tea Latte                                 0.733333   
Java Chip                                                 3.000000   
Java Chip (Without Whipped Cream)                         3.888889   
Mocha (Without Whipped Cream)                             1.266667   
Mocha                                                     0.466667   
Strawberries & Crème (Without Whipped Cream)              0.844444   
Vanilla Bean (Without Whipped Cream)                      0.600000   
Coffee                                                    0.633333   
Caramel                                                   0.066667   
Caramel (Without Whipped Cream)                           0.822222   
Iced Brewed Coffee (With Milk & Classic Syrup)            0.277778   
Caffè Americano                                           0.000000   
Espresso                                                  0.000000   
